const Images = {
    choosefile : require('../Images/input_image.png'),
    lego1 : require('../Images/1.png'),
    lego2 : require('../Images/2.png'),
    lego3 : require('../Images/3.png'),
    lego4 : require('../Images/4.png'),
    lego5 : require('../Images/5.png'),
    lego6 : require('../Images/6.png'),
    lego7 : require('../Images/7.png'),
    lego8 : require('../Images/8.png'),
    lego9 : require('../Images/9.png'),
    lego10 : require('../Images/10.png'),
    lego11 : require('../Images/11.png'),
    lego12 : require('../Images/12.png'),
    lego13 : require('../Images/13.png'),
    lego14 : require('../Images/14.png'),
    lego15 : require('../Images/15.png'),
    lego16 : require('../Images/16.png'),
    lego17 : require('../Images/17.png'),
    lego18 : require('../Images/18.png'),
    lego19 : require('../Images/19.png'),
    wave_hand : require('../Images/wave.png'),

    send : require('../Images/send.png'),
    input_file : require('../Images/pic.png'),
    sticker : require('../Images/sticker.png'),
}
export default Images